export const LANG = {
  vi: {
    // Navbar
    home: 'Trang chủ',
    products: 'Sản phẩm',
    hotDeals: 'Hot Deals',
    topUp: 'Top Nạp',
    reviews: 'Đánh giá',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    adminPanel: 'Admin Panel',
    balance: 'Số dư',
    deposit: 'Nạp tiền',
    buyNow: 'Mua ngay',
    history: 'Lịch sử',
    support: 'Hỗ trợ',
    dashboard: 'Dashboard',
    changePassword: 'Đổi mật khẩu',
    forgotPassword: 'Quên mật khẩu',
    referral: 'Giới thiệu',
    notifications: 'Thông báo',
    profile: 'Tài khoản',

    // Auth
    username: 'Tên đăng nhập',
    password: 'Mật khẩu',
    confirmPassword: 'Xác nhận mật khẩu',
    email: 'Email',
    referralCode: 'Mã giới thiệu (tùy chọn)',
    loginBtn: 'Đăng nhập',
    registerBtn: 'Đăng ký',
    oldPassword: 'Mật khẩu cũ',
    newPassword: 'Mật khẩu mới',

    // Products
    modSkill: 'Mod Skill',
    modFish: 'Mod Cá',
    modLevel: 'Mod Level',
    modItem: 'Mod Item',
    modPet: 'Mod Pet',
    modDiamond: 'Mod Kim Cương',
    modFull: 'Full Mod',
    banMod: 'Bản Mod (Tự Mod)',
    cauChung: 'Câu Chung (Theo Giờ)',
    scriptSniper: 'Sniper Arena',
    contact: 'Liên hệ',

    // Purchase
    selectService: 'Chọn dịch vụ',
    gameAccount: 'Tài khoản game',
    gamePassword: 'Mật khẩu game',
    voucherCode: 'Mã giảm giá',
    applyVoucher: 'Áp dụng',
    note: 'Ghi chú',
    totalPrice: 'Tổng tiền',
    confirmPurchase: 'Xác nhận mua',
    insufficientBalance: 'Không đủ số dư',

    // Deposit
    depositBank: 'Nạp qua Ngân hàng',
    depositCard: 'Nạp thẻ cào',
    amount: 'Số tiền',
    method: 'Phương thức',
    telco: 'Nhà mạng',
    cardSerial: 'Số Seri',
    cardCode: 'Mã thẻ',
    cardAmount: 'Mệnh giá',
    transferContent: 'Nội dung CK',
    submitDeposit: 'Gửi yêu cầu nạp',

    // Status
    pending: 'Chờ xử lý',
    completed: 'Hoàn thành',
    rejected: 'Từ chối',
    processing: 'Đang xử lý',
    cancelled: 'Đã hủy',

    // VIP
    vipLevel: 'Hạng VIP',
    vipDiscount: 'Giảm giá VIP',
    totalDeposited: 'Tổng nạp',
    totalSpent: 'Tổng chi',
    nextVip: 'VIP tiếp theo',
    needMore: 'Cần nạp thêm',

    // Misc
    cancel: 'Hủy',
    confirm: 'Xác nhận',
    close: 'Đóng',
    save: 'Lưu',
    delete: 'Xóa',
    search: 'Tìm kiếm',
    noData: 'Không có dữ liệu',
    loading: 'Đang tải...',
    success: 'Thành công',
    error: 'Lỗi',
    orderHistory: 'Lịch sử đơn hàng',
    depositHistory: 'Lịch sử nạp tiền',
    cardHistory: 'Lịch sử thẻ cào',
    cancelOrder: 'Hủy đơn',
    rate: 'Đánh giá',
    download: 'Tải xuống',
    copy: 'Sao chép',
    copied: 'Đã sao chép!',
    contactAdmin: 'Liên hệ Admin',
    workingHours: 'Giờ làm việc',
    heroTitle: 'KNOX SHOP',
    heroSubtitle: 'Mod Game Uy Tín - Giá Rẻ',
    heroDesc: 'Cửa hàng mod game Câu Cá Vạn Cân & Script Roblox hàng đầu',
    footerText: '© 2024 KNOX Shop. All rights reserved.',
    installApp: 'Cài đặt ứng dụng',
    installDesc: 'Thêm KNOX Shop vào màn hình chính để truy cập nhanh hơn!',
    installBtn: 'Cài đặt',
    notNow: 'Để sau',
    ticketSubject: 'Tiêu đề',
    ticketMessage: 'Nội dung',
    createTicket: 'Tạo Ticket',
    yourReferralCode: 'Mã giới thiệu của bạn',
    referredCount: 'Số người đã giới thiệu',
    referralBonus: 'Thưởng giới thiệu: +10.000đ/người',
    topDepositors: 'Top Nạp Tháng',
    price: 'Giá',
    game: 'Game',
    perHour: '/giờ',
    per1mDiamond: '/1tr KC',
  },
  en: {
    home: 'Home',
    products: 'Products',
    hotDeals: 'Hot Deals',
    topUp: 'Top Depositors',
    reviews: 'Reviews',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    adminPanel: 'Admin Panel',
    balance: 'Balance',
    deposit: 'Deposit',
    buyNow: 'Buy Now',
    history: 'History',
    support: 'Support',
    dashboard: 'Dashboard',
    changePassword: 'Change Password',
    forgotPassword: 'Forgot Password',
    referral: 'Referral',
    notifications: 'Notifications',
    profile: 'Account',

    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    email: 'Email',
    referralCode: 'Referral Code (optional)',
    loginBtn: 'Login',
    registerBtn: 'Register',
    oldPassword: 'Old Password',
    newPassword: 'New Password',

    modSkill: 'Mod Skill',
    modFish: 'Mod Fish',
    modLevel: 'Mod Level',
    modItem: 'Mod Item',
    modPet: 'Mod Pet',
    modDiamond: 'Mod Diamond',
    modFull: 'Full Mod',
    banMod: 'Mod Package (Self Mod)',
    cauChung: 'Shared Fishing (Per Hour)',
    scriptSniper: 'Sniper Arena',
    contact: 'Contact',

    selectService: 'Select Service',
    gameAccount: 'Game Account',
    gamePassword: 'Game Password',
    voucherCode: 'Voucher Code',
    applyVoucher: 'Apply',
    note: 'Note',
    totalPrice: 'Total',
    confirmPurchase: 'Confirm Purchase',
    insufficientBalance: 'Insufficient Balance',

    depositBank: 'Bank Transfer',
    depositCard: 'Phone Card',
    amount: 'Amount',
    method: 'Method',
    telco: 'Carrier',
    cardSerial: 'Serial Number',
    cardCode: 'Card Code',
    cardAmount: 'Denomination',
    transferContent: 'Transfer Content',
    submitDeposit: 'Submit Deposit',

    pending: 'Pending',
    completed: 'Completed',
    rejected: 'Rejected',
    processing: 'Processing',
    cancelled: 'Cancelled',

    vipLevel: 'VIP Level',
    vipDiscount: 'VIP Discount',
    totalDeposited: 'Total Deposited',
    totalSpent: 'Total Spent',
    nextVip: 'Next VIP',
    needMore: 'Need more',

    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    search: 'Search',
    noData: 'No data',
    loading: 'Loading...',
    success: 'Success',
    error: 'Error',
    orderHistory: 'Order History',
    depositHistory: 'Deposit History',
    cardHistory: 'Card History',
    cancelOrder: 'Cancel Order',
    rate: 'Rate',
    download: 'Download',
    copy: 'Copy',
    copied: 'Copied!',
    contactAdmin: 'Contact Admin',
    workingHours: 'Working Hours',
    heroTitle: 'KNOX SHOP',
    heroSubtitle: 'Trusted Game Mods - Best Prices',
    heroDesc: 'Top game mod shop for Câu Cá Vạn Cân & Roblox Scripts',
    footerText: '© 2024 KNOX Shop. All rights reserved.',
    installApp: 'Install App',
    installDesc: 'Add KNOX Shop to your home screen for faster access!',
    installBtn: 'Install',
    notNow: 'Not Now',
    ticketSubject: 'Subject',
    ticketMessage: 'Message',
    createTicket: 'Create Ticket',
    yourReferralCode: 'Your Referral Code',
    referredCount: 'People Referred',
    referralBonus: 'Referral Bonus: +10,000đ/person',
    topDepositors: 'Top Depositors',
    price: 'Price',
    game: 'Game',
    perHour: '/hour',
    per1mDiamond: '/1M diamonds',
  },
};

export type LangKey = keyof typeof LANG.vi;

export function detectLanguage(): 'vi' | 'en' {
  const saved = localStorage.getItem('knox_lang');
  if (saved === 'vi' || saved === 'en') return saved;
  const browserLang = navigator.language || (navigator as any).userLanguage || 'vi';
  return browserLang.startsWith('vi') ? 'vi' : 'en';
}
